---
title: "About me"
type: "about"
date: "11/02/2020"
---


Hi, I’m Abderrahmen Dhif.

I’am from Tunisia where I graduated from my engineer’s degree in statistics at Carthage university in 2015, then I moved to France and I completed my master’s degree in big data and machine learning at Reims university in 2016.

After finishing my studies, I started my career as a Data scientist/analyst in retail industry. Specifically, in marketing and customer insight department. My role is to analyse customer behaviours by using statistics and machine learning methods.

As a data scientist and analytics specialist, I have two kind of tasks, the first is analytical one, I develop a recurrent reports about customer behaviours to help marketing and CRM teams follow-up the impact of their actions and decisions. I also analyse customer data to find some customer insights. The second is developing machine learning models to solve marketing problems and to optimize targeting.  

I play basketball, when I'm not doing R or machine learning.